Loading config configs/cityscapes/semantic-segmentation/Base-Cityscapes-SemanticSegmentation.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.
Command Line Args: Namespace(config_file='configs/cityscapes/semantic-segmentation/maskformer2_R50_bs16_90k.yaml', dist_url='tcp://127.0.0.1:50347', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=['True'], resume=True)
Traceback (most recent call last):
  File "train_net.py", line 321, in <module>
    launch(
  File "/cpfs01/projects-HDD/pujianxiangmuzu_HDD/mr_22210240239/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_net.py", line 299, in main
    cfg = setup(args)
  File "train_net.py", line 290, in setup
    cfg.merge_from_list(args.opts)
  File "/home/mr_22210240239/.local/lib/python3.8/site-packages/fvcore/common/config.py", line 143, in merge_from_list
    return super().merge_from_list(cfg_list)
  File "/usr/local/lib/python3.8/dist-packages/yacs/config.py", line 223, in merge_from_list
    _assert_with_logging(
  File "/usr/local/lib/python3.8/dist-packages/yacs/config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: Override list has odd length: ['True']; it must be a list of pairs
